package enums;

public enum InventorySort {

	MONITORING, TELEPORT, FREEZE, GAMEMODE, FOOD, LEVEL, HEALTH, INVENTORY, ENDERCHEST, INVENTORY_EXTRA,
	ENCHANTING_INV_CHOOSE, ENCHANTMENTS, ENCHANTING_LVL1, ENCHANTING_LVL2, ENCHANTING_LVL3, ENCHANTING_LVL4,
	ENCHANTING_LVL5, ENCHANTING_ITEM_CHOOSE, ENCHANTING_ITEM_CHOOSE_EXTRA, ENCHANTING_ITEM_CHOOSE_EC
}
